name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip build dpkt
    - name: Build binary package
      run: python -m build -w
    - name: Build source package
      run: python -m build -s
      if: matrix.python-version == '3.11'
    - name: Install package
      run: python -m pip install dist/fnfqueue*whl
    - name: setup nfqueue
      run: sudo iptables -A INPUT -j NFQUEUE -i lo --dst 127.0.0.2 --queue-num 1
    - name: run tests
      working-directory: test
      run: |
        sudo `which python` ping_test.py
        sudo `which python` flood_test.py short
        sudo `which python` close_test.py short
    - name: store built packages
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.python-version }}
        path: dist/*
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - run: ls -R
      working-directory: dist